# Generated by Django 3.0.5 on 2020-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('message_content', models.CharField(max_length=160)),
                ('sent_datetime', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': '-sent_datetime',
            },
        ),
    ]
